import { Linking, Alert } from 'react-native';

/**
 * Triggers the "Add to Google Wallet" flow using a pre-generated JWT.
 * This function does NOT create the pass; it only initiates the save process
 * on the client-side. The JWT must be generated by your secure backend server.
 *
 * @param jwt - The JSON Web Token representing the pass, provided by your backend.
 */
export const triggerAddToWalletFlow = async (jwt: string): Promise<void> => {
  if (!jwt) {
    Alert.alert("Error", "Cannot add to wallet. The pass token is missing.");
    return;
  }

  const url = `https://pay.google.com/gp/v/save/${jwt}`;

  try {
    // Check if the Google Pay/Wallet app is available or if a browser can handle the link
    const supported = await Linking.canOpenURL(url);

    if (supported) {
      // Open the link to start the save process
      await Linking.openURL(url);
    } else {
      Alert.alert("Error", "Cannot open the link. Please ensure you have a web browser or the Google Wallet app installed.");
    }
  } catch (error) {
    console.error("Failed to trigger Add to Wallet flow:", error);
    Alert.alert("Error", "An unexpected error occurred while trying to add the pass to your wallet.");
  }
};